jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: mkdir build
    displayName: Make build directory
  - task: CMake@1
    displayName: Building with CMake
    inputs:
      workingDirectory: 'build'
      #cmakeArgs: '..'
  