jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - checkout: self
    submodules: true
  - script: mkdir build
    displayName: Make build directory
  - task: CMake@1
    displayName: Building with CMake
    inputs:
      cmakeArgs: '..'
  - script: |
        cd build
        make
    displayName: 'Run make'
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    submodules: true
  - script: mkdir build
    displayName: Make build directory
  - task: CMake@1
    displayName: Building with CMake
    inputs:
      cmakeArgs: '..'
  - task: MSBuild@1
    inputs:
      solution: 'build/ALL_BUILD.vcxproj'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      displayName: 'Run make'