jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: 
    mkdir build
    displayName: Make build directory
- task: CMake@1
  inputs:
    workingDirectory: 'build'
    displayName: Building with CMake
    cmakeArgs: '..'
  